version: "3.8"
services:
    web:
        #build: 
        #    context: .
        #    dockerfile: ./Doctors_practice/Dockerfile
        image: msabljak/doctors_practice:latest
        expose:
            - "8000"
        depends_on: 
            - db
            - amq
            - eventstore_db
            - identityservice
            - elasticsearch
        environment: 
            DBServer: "db"
    identityservice:
        image: msabljak/identityservice:latest
        expose: 
            - "5001"
        ports:
            - "5001:5001"
        depends_on: 
            - db
        environment: 
            DBServer: "db"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
        ports:
            - "1433:1433"
        environment: 
            SA_PASSWORD: "<QWerT!13r4>"
            ACCEPT_EULA: "Y"
        volumes: 
            - "./Doctors_practice/SQLdata/Doctors_practice:/var/opt/mssql/data"
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
            - identityservice
        ports:
            - "4000:4000"
            - "4001:4001"
    amq:
        image: rmohr/activemq
        ports:
            - "61616:61616"
            - "8161:8161"
    emailservice:
        image: msabljak/emailservice:latest   
        depends_on: 
            - amq
        restart: always
    eventstore_db:
        image: eventstore/eventstore
        command: --dev --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_INT_TCP_PORT=1112
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_INT_HTTP_PORT=2112
            - EVENTSTORE_EXT_HTTP_PORT=2113
        ports:
            - 1113:1113
            - 2113:2113
        volumes:
            - "./Doctors_practice/EventStoreData:/var/lib/eventstore"
        restart: always
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        ports: 
            - 9200:9200
            - 9300:9300
        environment: 
            - discovery.type=single-node
        volumes: 
            - "./Doctors_practice/Elasticsearch/data:/usr/share/elasticsearch/data"
    elasticsearchindexrefresherservice:
        image: msabljak/elasticsearchindexrefresherservice:latest
        depends_on:
            - web
        restart: always
#    mongo:
#        image: mongo:latest
#        ports: 
#            - 27017:27017
#        restart: always
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example
#        volumes:
#            - "./Doctors_practice/MongoDB:/data/db"