version: "3.8"
services: 
    web:
        build: "./Doctors_practice"
        expose: 
            - "8000"
        depends_on:
            - db
        environment: 
            DBServer: "db"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
        ports:
            - "1433:1433"
        environment: 
            SA_PASSWORD: "<QWerT!13r4>"
            ACCEPT_EULA: "Y"
        volumes: 
            - "./Doctors_practice/SQLdata/Doctors_practice:/var/opt/mssql/data"
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
        ports:
            - "4000:4000"
    amq:
        image: rmohr/activemq
        ports:
            - "61616:61616"
            - "8161:8161"            
